<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "dropbox_carousel"
 *
 * Auto generated by Extension Builder 2013-04-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Dropbox Carousel',
	'description' => 'Read photos from dropbox and output as Twitter Bootstrap carousel.',
	'category' => 'plugin',
	'author' => 'Visay Keo',
	'author_email' => 'visay.keo@typo3.org',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1-dev',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
			'fal_dropbox' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>